version: '2'

services:

  # The Application
  app:
    build:
      context: ./../
      dockerfile: laravel-docker/app.dockerfile
    links:
      - mysql
    depends_on:
      - mysql
    working_dir: /var/www
    volumes:
      - ./../:/var/www

  # The Web Server
  web:
    build:
      context: ./../
      dockerfile: laravel-docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The database 
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_HOST: mysql
    volumes:
      - db:/var/lib/mysql

volumes:
  db:


